### ISSUE TITLE
为什么读缓存时要强制重新设置 etag 和 last-modified？

### ISSUE THREAD

**Issue by azh18** [TeaOSLab/EdgeNode#1]
![image](https://user-images.githubusercontent.com/11980692/211541153-b9a4064a-b758-4258-b0bd-ad42ef3bcba1.png)
看源码，这里有一点没有理解，如果数据一致的话，etag和last-modified 应该也要和源站保持一致？带有 if-modified-since 时源站返回304 应该也是正确的？为什么要避免呢？

**Comment by azh18** [comment]
internal/nodes/http_request_cache.go

**Comment by iwind** [comment]
代码注释里已经写了，避免源站返回304，具体说来，是因为源站如果返回304，就不会携带源站内容，边缘节点就无法缓存源站内容，这样就会导致每次用户请求都需要回源，从而无法有效减少源站负载。
