### ISSUE TITLE
节点编译错误

### ISSUE THREAD

**Issue by qqq-1123** [TeaOSLab/EdgeNode#6]
root@localhost:~/EdgeNode/build# go version
go version go1.18.1 linux/amd64
root@localhost:~/EdgeNode# cp build/configs/api.template.yaml build/configs/api.yaml          
root@localhost:~/EdgeNode# vi build/configs/api.yaml 
root@localhost:~/EdgeNode# cd build/
root@localhost:~/EdgeNode/build# ./build.sh linux amd64
checking ...
building v1.2.1/linux/amd64/community ...
copying ...
building ...
 github.com/TeaOSLab/EdgeNode/internal/nodes
../internal/nodes/http_request_reverse_proxy.go:289:49: assignment mismatch: 5 variables but this.doOSSOrigin returns 4 values
zip files
/root/EdgeNode/build
OK

**Comment by iwind** [comment]
fixed
